import {Box} from '@chakra-ui/react';

import Head from 'next/head';

import Sidebar from './Sidebar';

const Wrapper = ({children}) => {
  
  return (
    <Box>
      <Head>
        <title>INTRANET</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/intranet.png' />
      </Head>
      <Sidebar/>
      <Box width='600px' margin='auto'>
        {children}
      </Box>
    </Box>
  );
};

export default Wrapper;
